export const SAVE_POST_REQUEST = "SAVE_POST_REQUEST";
export const FETCH_POST_REQUEST = "FETCH_POST_REQUEST";
export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";
export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const POST_SUCCESS = "POST_SUCCESS";
export const POST_FAILURE = "POST_FAILURE";

export const POST_CATEGORIES = "POST_CATEGORIES";
